instances:
  gpdb:
    - host: "chorus-gpdb42"
      port: 5432
      maintenance_db: "postgres"
      account:
        db_username: "gpadmin"
        db_password: "secret"

    - host: "chorus-gpdb41"
      port: 5432
      maintenance_db: "postgres"
      account:
        db_username: "gpadmin"
        db_password: "secret"

    - host: "chorus-gpdb40"
      port: 5432
      maintenance_db: "postgres"
      account:
        db_username: "gpadmin"
        db_password: "secret"

    - host: "local-greenplum"
      port: 5432
      maintenance_db: "postgres"
      account:
        db_username: "vagrant"
        db_password: "secret"

  hadoop:
    - host: "chorus-gphd02"
      port: 8020
      username: "pivotal"