jruby: http://jruby.org.s3.amazonaws.com/downloads/1.7.0/jruby-complete-1.7.0.jar
jetty: http://dist.codehaus.org/jetty/jetty-hightide-7.4.5/jetty-hightide-7.4.5.v20110725.zip
jruby-rack: http://repository.codehaus.org/org/jruby/rack/jruby-rack/1.0.10/jruby-rack-1.0.10.jar
app_root: $CHORUS_HOME
java_options: $CHORUS_JAVA_OPTIONS
ruby_version: 1.9
app_type: rack
http_port: 3000
bundle_without: [integration, development, test, packaging, ci_jasmine, ci_legacy_migration]
max_concurrent_connections: 20
